from django.db import models

class ShortURL(models.Model):
    # Short URL's primary key
    id = models.AutoField(primary_key=True)
    # Original URL
    original_url = models.URLField(max_length=200)
    # Shortened URL (generated by the system)
    short_code = models.CharField(max_length=50, unique=True)
    # Date when the short URL was created
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.original_url
